#!/bin/sh
lock() {
    /home/hendrik/.config/i3/scripts/lock.sh
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        /home/hendrik/.config/i3/scripts/suspend.sh
        ;;
    reboot)
        /home/hendrik/.config/i3/scripts/reboot.sh
        ;;
    shutdown)
        /home/hendrik/.config/i3/scripts/shutdown.sh
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 0
